# Generated by Django 3.2.8 on 2021-10-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nombre')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefono')),
                ('localizacao', models.TextField(verbose_name='localizacion')),
                ('whatsapp', models.TextField(verbose_name='whatsapp')),
                ('slogan', models.CharField(max_length=200, verbose_name='slogan')),
                ('orário_funcionamento', models.CharField(max_length=100, verbose_name='Orário')),
                ('email', models.CharField(max_length=100, verbose_name='correo electronico')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('descricao', models.TextField(verbose_name='descripcion')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precio')),
            ],
        ),
    ]
